/* PROJECTS */
export const GET_BUILDER = "GET_BUILDER"
export const GET_BUILDER_SUCCESS = "GET_BUILDER_SUCCESS"
export const GET_BUILDER_FAIL = "GET_BUILDER_FAIL"

/* PROJECTS DETAIL*/
export const GET_BUILDER_DETAIL = "GET_PROJECT_DETAIL"
export const GET_BUILDER_DETAIL_SUCCESS = "GET_BUILDER_DETAIL_SUCCESS"
export const GET_BUILDER_DETAIL_FAIL = "GET_BUILDER_DETAIL_FAIL"

export const ADD_NEW_BUILDER = "ADD_NEW_BUILDER"
export const ADD_BUILDER_SUCCESS = "ADD_BUILDER_SUCCESS"
export const ADD_BUILDER_FAIL = "ADD_BUILDER_FAIL"

export const UPDATE_BUILDER = "UPDATE_BUILDER"
export const UPDATE_BUILDER_SUCCESS = "UPDATE_BUILDER_SUCCESS"
export const UPDATE_BUILDER_FAIL = "UPDATE_BUILDER_FAIL"

export const DELETE_BUILDER = "DELETE_BUILDER"
export const DELETE_BUILDER_SUCCESS = "DELETE_BUILDER_SUCCESS"
export const DELETE_BUILDER_FAIL = "DELETE_BUILDER_FAIL"